<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../admin/src/NexusAuth.Workbench.Api/NexusAuth.Workbench.Api.csproj" />
    <ProjectReference Include="../../src/NexusAuth.Application/NexusAuth.Application.csproj" />
    <ProjectReference Include="../../src/NexusAuth.Host/NexusAuth.Host.csproj" />
  </ItemGroup>
</Project>
