export const getMenuList = () => {
    return new Promise<Array<any>>((resolve) => {
        window.setTimeout(() => {
            resolve([
                {
                    id: '1',
                    route: '/dashboard',
                    componentPath: '/dashboard/index.tsx',
                    name: '仪表盘',
                    show: true,
                    iconName: "dashboard",
                    parentId: null,
                    parentPaths: Array<string>,
                    children: [],
                },
                {
                    id: 'oauth',
                    route: '/oauth',
                    componentPath: null,
                    name: 'OAuth 管理',
                    show: true,
                    iconName: "lock",
                    parentId: null,
                    parentPaths: Array<string>,
                    children: []
                },
                {
                    id: 'oauth-client',
                    route: '/oauth/client-management',
                    componentPath: '/client-management/index.tsx',
                    name: 'Client 管理',
                    show: true,
                    iconName: null,
                    parentId: 'oauth',
                    parentPaths: Array<string>,
                    children: [],
                },
                {
                    id: 'oauth-user',
                    route: '/oauth/user-management',
                    componentPath: '/user-management/index.tsx',
                    name: '用户管理',
                    show: true,
                    iconName: null,
                    parentId: 'oauth',
                    parentPaths: Array<string>,
                    children: [],
                },
                {
                    id: 'oauth-api-resource',
                    route: '/oauth/api-resource-management',
                    componentPath: '/api-resource-management/index.tsx',
                    name: 'API 资源管理',
                    show: true,
                    iconName: null,
                    parentId: 'oauth',
                    parentPaths: Array<string>,
                    children: [],
                },
                {
                    id: '3',
                    route: '/ai-agent',
                    componentPath: '/ai-agent/index.tsx',
                    name: '智 V V ',
                    show: true,
                    iconName: "aiAgent",
                    parentId: null,
                    parentPaths: Array<string>,
                    children: [],
                },
                {
                    id: '2',
                    route: '/ancillary',
                    componentPath: null,
                    name: '验证配置',
                    show: true,
                    iconName: "ruleConfig",
                    parentId: null,
                    parentPaths: Array<string>,
                    children: []
                },
                {
                    id: '2-2',
                    route: '/field-value-mapping-config',
                    componentPath: '/field-value-mapping-config/index.tsx',
                    name: '字段取值配置',
                    show: true,
                    iconName: null,
                    parentId: '2',
                    parentPaths: Array<string>,
                    children: []
                },
                {
                    id: '2-3',
                    route: '/product-config',
                    componentPath: '/product-config/index.tsx',
                    name: '产品配置',
                    show: true,
                    iconName: null,
                    parentId: '2',
                    parentPaths: Array<string>,
                    children: []
                },
                {
                    id: '2-4',
                    route: '/sale-ref-id-mapping-config',
                    componentPath: '/sale-ref-id-mapping-config/index.tsx',
                    name: 'saleRefId 映射配置',
                    show: true,
                    iconName: null,
                    parentId: '2',
                    parentPaths: Array<string>,
                    children: []
                },
                {
                    id: '2-5',
                    route: '/company-subject-mapping-config',
                    componentPath: '/company-subject-mapping-config/index.tsx',
                    name: '公司主体映射配置',
                    show: true,
                    iconName: null,
                    parentId: '2',
                    parentPaths: Array<string>,
                    children: []
                },
                {
                    id: '2-6',
                    route: '/dictionary-config',
                    componentPath: '/dictionary-config/index.tsx',
                    name: '字典配置',
                    show: true,
                    iconName: null,
                    parentId: '2',
                    parentPaths: Array<string>,
                    children: []
                },
            ])
        })
    })
}
